baseURL = 'https://meshcore-vrn.diadlo.ru/'
locale = 'ru-ru'
title = 'MeshCore Воронеж'
theme = 'hugo-book'

[markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.home]]
  name = 'Telegram'
  pageRef = 'https://t.me/meshcoreVRN'
  weight = 1

